### PR TITLE
[Task 6] Created data visualizations

### PR DESCRIPTION
**Pull request by tyreest19**
## Description

Summary of the change.

ADDED:
IMPROVED:
FIXED:
REMOVED:

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which improves functionality)

## Checklist:

- [ ] Title is in "[Task #] Description" format
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by YanceyR** [comment]
Please fill out the pr description so the team can know what is going on.

**Comment by YanceyR** [comment]
Do you think we should add percentage labels on the pie charts to add clarity?

**Comment by tyreest19** [comment]
Fixed it in this pull request https://github.com/Johnsons-AI/Tic-Tac/pull/8

**Comment by tyreest19** [comment]
Fixed it in this pull request #8

**Pull request closed without merging**
