### PR TITLE
[Task #1] Change Dictionary Value Type PR

### PR DESCRIPTION
**Pull request by leronjulian**
## Description

Made the values for the dictionary an array instead of a string. This makes Task #2 easier.

IMPROVED: Dictionary values

## Type of change

- [x] Improvement (non-breaking change which improves functionality)

## Checklist:

- [x] Title is in "[Task #] Description" format
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by YanceyR** [comment]
Can you screenshot some keys:values in the dict.

**Comment by leronjulian** [comment]
Wouldn't it return in the form [[1], [1]] and not [[1][1]] ? I don't think you can make a list that looks like [[1][1]] in python

**Comment by leronjulian** [comment]
screen shot 2018-11-25 at 3 14 41 pm

Test of the values in the dictionary

**Comment by leronjulian** [comment]
screen shot 2018-11-25 at 3 52 34 pm

Test of the values in the dictionary (Updated)

**Comment by YanceyR** [comment]
What are the keys? Are they still strings? Make sure to pull changes also.

**Comment by leronjulian** [comment]
Yeah the keys are still strings. I spoke with Zane about it. Should I pull and commit those changes to this PR?

**Comment by YanceyR** [comment]
Looks good! Just link up with @zwhitfield3 on rendering the board.

**Pull request merged**
